
            <input class="form-control" name="prods" id="prods" placeholder="Filtra Pokemons por nombre">                    
            <br>
            <button onclick="BuscaPokemons(document.getElementById('prods').value)" class="btn btn-primary">Busca!</button>
            <br><br>
            <div class="container text-center">
                <div class="row" id="divpokemons">
                    
                </div>
            </div>
        </div>
    </body>
</html>

